# Generated by Django 6.0.3 on 2026-04-18 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_project_created_at_projecttask_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('team', 'title'), name='unique_project_title_per_team'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_project_task_title_per_project'),
        ),
    ]
